package com.digipet.care.enums;

public enum TipoServico {
    BANHO_E_TOSA, CONSULTA_VETERINARIA, VACINACAO, HOSPEDAGEM, PET_SITTER,
    TELEORIENTACAO, FISIOTERAPIA, CRECHE, ACUPUNTURA, EXAME_LABORATORIAL,
    CIRURGIA, OUTRO
}
